### ISSUE TITLE
putImageSize crashed on some devices

### ISSUE THREAD

**Issue by sm2017** [react-native-community/react-native-cameraroll#226]
# Bug report

## Summary

putImageSize crashed on some devices

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 2.80 GB / 11.85 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-28 | Intel x86
 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 1.8.0_221 - C:\Program Files\Java\jdk1.8.0_221\bin\javac.EXE
    Python: 2.7.16 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found


```

Library version: 4.0.0

## Steps to reproduce

It happens on some android devices , I dont know how we can reproduce it
I have crashlytics log
![image](https://user-images.githubusercontent.com/19644997/91717860-8dd78900-eba7-11ea-86d1-99af26e6442c.png)
![image](https://user-images.githubusercontent.com/19644997/91717874-93cd6a00-eba7-11ea-95a4-f933b5a8ed50.png)

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.AssetFileDescriptor.close()' on a null object reference
       at com.reactnativecommunity.cameraroll.CameraRollModule.putImageSize(CameraRollModule.java:715)
       at com.reactnativecommunity.cameraroll.CameraRollModule.putImageInfo(CameraRollModule.java:572)
       at com.reactnativecommunity.cameraroll.CameraRollModule.putEdges(CameraRollModule.java:519)
       at com.reactnativecommunity.cameraroll.CameraRollModule.access$300(CameraRollModule.java:64)
       at com.reactnativecommunity.cameraroll.CameraRollModule$GetMediaTask.doInBackgroundGuarded(CameraRollModule.java:396)
       at com.reactnativecommunity.cameraroll.CameraRollModule$GetMediaTask.doInBackgroundGuarded(CameraRollModule.java:275)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:36)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

## Reproducible sample code

```js
 CameraRoll.getPhotos({
       first: 20,
       assetType: 'All',
       include: ['filename', 'imageSize']
     })
```

**Comment by sm2017** [comment]
@bartolkaruza Can you please take a look?

**Comment by nitnk9** [comment]
Having same problem on Xiaomi Android 10.

**Comment by sm2017** [comment]
Reply please .....

**Comment by sharifashraful** [comment]
any solution???

**Comment by sharifashraful** [comment]
![image](https://user-images.githubusercontent.com/7131239/94091909-4311ff80-fe3b-11ea-9e78-20c0775ec2be.png)

**Comment by mikbry** [comment]
I think my bug #239 is related to this bug. I could reproduce it with files empty file size.

**Comment by JuraSemenenko** [comment]
[https://github.com/react-native-community/react-native-cameraroll/blob/c99c28c9a4e883ab8950763be19a2034be9378fc/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L716](url)

There is problem in this line, i think. photoDescriptor can be nul, but we don't catch NullPointerException

**Comment by german970814** [comment]
@bartolkaruza still happening.

```
>>> cat node_modules/@react-native-community/cameraroll/package.json |grep version
>>> "version": "4.0.1",
```

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:142)
	at com.reactnativecommunity.cameraroll.CameraRollModule.putImageSize(CameraRollModule.java:686)
	at com.reactnativecommunity.cameraroll.CameraRollModule.putImageInfo(CameraRollModule.java:572)
	at com.reactnativecommunity.cameraroll.CameraRollModule.putEdges(CameraRollModule.java:519)
	at com.reactnativecommunity.cameraroll.CameraRollModule.access$300(CameraRollModule.java:64)
	at com.reactnativecommunity.cameraroll.CameraRollModule$GetMediaTask.doInBackgroundGuarded(CameraRollModule.java:396)
	at com.reactnativecommunity.cameraroll.CameraRollModule$GetMediaTask.doInBackgroundGuarded(CameraRollModule.java:275)
	at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:36)
	at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

Tested in `Android 10` and `Redmi Note 8 Pro`
